library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;


entity axi_read_channel is
  generic (
            -- Users can add generic parameters here

            -- User parameters ends
            C_M_TARGET_SLAVE_BASE_ADDR : std_logic_vector	:= x"00000000"; -- Base address of targeted slave
            C_M_AXI_BURST_LEN	     : integer	:= 1; -- Burst Length. Supports 1, 2, 4, 8, 16, 32, 64, 128, 256 burst lengths
            C_M_AXI_ID_WIDTH	     : integer	:= 1; -- Thread ID Width
            C_M_AXI_ADDR_WIDTH	   : integer	:= 32; -- Width of Address Bus
            C_M_AXI_DATA_WIDTH	   : integer	:= 32; -- Width of Data Bus
            C_M_AXI_AWUSER_WIDTH   : integer	:= 0; -- Width of User Write Address Bus
            C_M_AXI_ARUSER_WIDTH   : integer	:= 0; -- Width of User Read Address Bus
            C_M_AXI_WUSER_WIDTH	   : integer	:= 0; -- Width of User Write Data Bus
            C_M_AXI_RUSER_WIDTH	   : integer	:= 0; -- Width of User Read Data Bus
            C_M_AXI_BUSER_WIDTH	   : integer	:= 0  -- Width of User Response Bus
          );
  port (
         clk : in std_logic;
         rst: in std_logic;

         start : in std_logic;
         addr : in std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);
         rdata : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);
         raddr : out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0);
         ready : out  std_logic;

         M_AXI_ARID	: out std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0); -- Master Interface Read Address.
         M_AXI_ARADDR	: out std_logic_vector(C_M_AXI_ADDR_WIDTH-1 downto 0); -- Read address. This signal indicates the initial address of a read burst transaction.
         M_AXI_ARLEN	: out std_logic_vector(7 downto 0); -- Burst length. The burst length gives the exact number of transfers in a burst
         M_AXI_ARSIZE	: out std_logic_vector(2 downto 0); -- Burst size. This signal indicates the size of each transfer in the burst
         M_AXI_ARBURST	: out std_logic_vector(1 downto 0); -- Burst type. The burst type and the size information, determine how the address for each transfer within the burst is calculated.
         M_AXI_ARLOCK	: out std_logic; -- Lock type. Provides additional information about the atomic characteristics of the transfer.
         M_AXI_ARCACHE	: out std_logic_vector(3 downto 0); -- Memory type. This signal indicates how transactions are required to progress through a system.
         M_AXI_ARPROT	: out std_logic_vector(2 downto 0); -- Protection type. This signal indicates the privilege and security level of the transaction, and whether the transaction is a data access or an instruction access.
         M_AXI_ARQOS	: out std_logic_vector(3 downto 0); -- Quality of Service, QoS identifier sent for each read transaction
         M_AXI_ARUSER	: out std_logic_vector(C_M_AXI_ARUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
         M_AXI_ARVALID	: out std_logic; -- Write address valid. This signal indicates that the channel is signaling valid read address and control information
         M_AXI_ARREADY	: in std_logic; -- Read address ready. This signal indicates that the slave is ready to accept an address and associated control signals
                                       -- AXI Read Data Channel
         M_AXI_RID	: in std_logic_vector(C_M_AXI_ID_WIDTH-1 downto 0); -- Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave.
         M_AXI_RDATA	: in std_logic_vector(C_M_AXI_DATA_WIDTH-1 downto 0); -- Master Read Data
         M_AXI_RRESP	: in std_logic_vector(1 downto 0); -- Read response. This signal indicates the status of the read transfer
         M_AXI_RLAST	: in std_logic; -- Read last. This signal indicates the last transfer in a read burst
         M_AXI_RUSER	: in std_logic_vector(C_M_AXI_RUSER_WIDTH-1 downto 0); -- Optional User-defined signal in the read address channel.
         M_AXI_RVALID	: in std_logic; -- Read valid. This signal indicates that the channel is signaling the required read data.
         M_AXI_RREADY	: out std_logic -- Read ready. This signal indicates that the master can accept the read data and response information.
       );
end entity axi_read_channel;

--fuse on a recordtype
architecture rtl of axi_read_channel is
  type RAC_state_t is (RESET, INIT, ACCEPT, WAITING);
  signal RAC_state,RAC_state_next, RAC_state_next_i: RAC_state_t;
  signal RAC_INIT_next, RAC_ACCEPT_next, RAC_WAITING_next, RAC_ACCEPT, RAC_INIT: RAC_state_t;

  type RC_state_t is (RESET, WAITING, ACCEPT);
  signal RC_state,RC_state_next: RC_state_t;

  signal ar_latch_enable, read_start, read_done : std_logic;
begin
 ----------------------------------------------------------------------------------------
  --Storage for RAC
  RAC_state <= RAC_state_next when rising_edge(clk);
  RAC_state_next <= RESET when rst = '1' else RAC_state_next_i;

  with RAC_state select RAC_state_next_i <= RAC_INIT_next when RAC_INIT,
  RAC_ACCEPT_next when RAC_ACCEPT,
  RAC_WAITING_next when others;

  RAC_INIT_next <= ACCEPT when M_AXI_ARREADY = '1' else INIT;
  RAC_ACCEPT_next <= WAITING when read_done = '1' else ACCEPT;
  RAC_WAITING_next <= INIT when start = '1' else WAITING;

  -- Mealy outputs for RAC state machine 
  ar_latch_enable <= '1' when RAC_state = WAITING and start = '1' else '0';
  M_AXI_ARVALID <= ar_latch_enable;
  read_start <= '1' when RAC_state = INIT and M_AXI_ARREADY = '1' else '0';

  -- More outputs for RAC state machine 
  ready <= '1' when RAC_state = WAITING else '0';

 ----------------------------------------------------------------------------------------
  --Storage for RC
 ----------------------------------------------------------------------------------------
  raddr_reg : entity work.gen_reg
  generic map (
                N => 32 
              )
  port map (
             clk => clk,
             d => addr,
             q => M_AXI_ARADDR,
             reset => rst,
             enable => ar_latch_enable
           ); 
end architecture rtl;
